{% set versions = {
    "master": "d080e301ec71061c46049d23fedfb8106be3153f"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "curlpp")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://github.com/jpbarrette/curlpp"
  git_rev: {{ versions.get(version, "HEAD") }}
  patches:
    - patches/conda.patch

requirements:
  build:
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('c') }}   # [linux]
    - {{ stdlib('c') }}

    - cmake
    - make

  host:
    - libcurl
    
  run:
    - libcurl

about:
  home: "https://github.com/jpbarrette/curlpp"
  license: "MIT"
  summary: "cURLpp is a C++ wrapper for libcURL"
  description: |
    a free and easy-to-use client-side URL transfer library, supporting FTP, FTPS, HTTP, HTTPS, GOPHER, TELNET, DICT, FILE and LDAP. libcurl supports HTTPS certificates, HTTP POST, HTTP PUT, FTP uploading, kerberos, HTTP form based upload, proxies, cookies, user+password authentication, file transfer resume, http proxy tunneling and more!

extra:
  recipe-maintainers:
    - meiyasan
